#if !canImport(ObjectiveC)
import XCTest

extension BasicAuthTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BasicAuthTests = [
        ("testCreateBasicAuth", testCreateBasicAuth),
    ]
}

extension ClientTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ClientTests = [
        ("testExample", testExample),
        ("testPerformanceExample", testPerformanceExample),
    ]
}

extension EncodableParameterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EncodableParameterTests = [
        ("testWhenCreateEncodableParameter", testWhenCreateEncodableParameter),
    ]
}

extension FormParametersTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FormParametersTests = [
        ("testWhenFormParametersTests", testWhenFormParametersTests),
    ]
}

extension JSONParametersTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__JSONParametersTests = [
        ("testWhenCreateJSONParameters", testWhenCreateJSONParameters),
    ]
}

extension QueryParametersTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__QueryParametersTests = [
        ("testWhenCreateQueryParameters", testWhenCreateQueryParameters),
    ]
}

extension StringParameterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StringParameterTests = [
        ("testWhenCreateStringParameter", testWhenCreateStringParameter),
    ]
}

extension UtilitiesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UtilitiesTests = [
        ("testAppendingPathComponent", testAppendingPathComponent),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(BasicAuthTests.__allTests__BasicAuthTests),
        testCase(ClientTests.__allTests__ClientTests),
        testCase(EncodableParameterTests.__allTests__EncodableParameterTests),
        testCase(FormParametersTests.__allTests__FormParametersTests),
        testCase(JSONParametersTests.__allTests__JSONParametersTests),
        testCase(QueryParametersTests.__allTests__QueryParametersTests),
        testCase(StringParameterTests.__allTests__StringParameterTests),
        testCase(UtilitiesTests.__allTests__UtilitiesTests),
    ]
}
#endif
