#if !canImport(ObjectiveC)
import XCTest

extension ReachabilityTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ReachabilityTests = [
        ("testExample", testExample),
        ("testPerformanceExample", testPerformanceExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ReachabilityTests.__allTests__ReachabilityTests),
    ]
}
#endif
